version: '3.8'

services:
  frontend:
    build:
      context: ./insurance-recommendation  # Path to the frontend Dockerfile
    ports:
      - "80:80"  # Map frontend container port to host (port 80 is the default for Nginx)
    environment:
      REACT_APP_API_URL: "http://backend:5000"  # Communicate with the backend via service name
    depends_on:
      - backend  # Wait for backend to be started (optional, but helps control startup order)

  backend:
    build:
      context: ./insur-rec-backend  # Path to the backend Dockerfile
    ports:
      - "5000:5000"  # Map backend container port to host
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}  # This will reference the value from the .env file
